spring:
  cloud:
    nacos:
      discovery:
        server-addr: 106.55.246.217:8848
        ip: 106.55.246.217
    sentinel:
      transport:
        dashboard: 106.55.246.217:9001
      datasource:
        - nacos:
            server-addr: 106.55.246.217:8848
            data-id: gateway-sentinel
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - predicates:
            - Path=/user/**
          uri: lb://service-provider
          id: service-provider
