server:
  port: 8001
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 106.55.246.217:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - predicates:
            - Path=/user/**
          uri: lb://service-provider
          id: service-provider
